modLoader = "javafml"
loaderVersion = "[4.0,)"
license = "MIT"
issueTrackerURL = "https://github.com/yourusername/ChippedGraver/issues"

[[mods]]
modId = "chippedgraver"
version = "1.0.1"
displayName = "Chipped Graver"
description = "A tool to randomize Chipped mod blocks"
authors = ["Ceethru"]

[[dependencies.chippedgraver]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"

[[dependencies.chippedgraver]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.22)"

[[dependencies.chippedgraver]]
modId = "chipped"
mandatory = false
versionRange = "[4.0.2,)"
